### ISSUE TITLE
Add ASO Snow off data to DB

### ISSUE THREAD

**Issue by micahjohnson150** [hpmarshall/SnowEx2020_SQLcode#10]
Download the 2016 Data from the NSIDC and upload to the database

**Comment by micahjohnson150** [comment]
@hpmarshall I looked for the Snow off data in the NSIDC, I searched ASO and Grand Mesa and didn't see anything I thought should be it. Is it under a different name or am I just missing it?

**Comment by hpmarshall** [comment]
@micahjohnson150 Strange...data access has been pretty variable, not sure what is going on.  I'm uploading all the ASO data from 2016-17 to the SnowEx2020_QSI Google Drive folder now.  It was in UTM Zone 13, so we will need to reproject to Zone 12.  I'll shoot you a note as soon as its uploaded.  There are 2 files for 2016, one is the veg model, and one is the bare earth model.  Then there is also several snow depth products  from 2017 - for these we want the ones ending in "recode".  I'll shoot you a note once they are uploaded.  Thanks!

**Comment by micahjohnson150** [comment]
Fixed by https://github.com/hpmarshall/SnowEx2020_SQLcode/commit/525d8600edd41a64a22d42c6f09e2ef5f4503cfc
