### ISSUE TITLE
Make a script to add Elevation Products (3DEP) 1m DEM products to DB

### ISSUE THREAD

**Issue by micahjohnson150** [hpmarshall/SnowEx2020_SQLcode#4]
Here's the link to access snow-free LiDAR 1m DEM from Grand Mesa:
https://viewer.nationalmap.gov/basic/

Download for grand mesa, create a script to download them. Sounds like it will download almost all of the data for the area flown.

**Comment by hpmarshall** [comment]
3DEP is the USGS project, and the product we want is the 1m DEM (which is snow free).  Its available for a bunch of places in the US (goal is everywhere by 2023), and we want to access just the data that matches the bounding box of the snow-on lidar data already in the database.  We will be missing some snow-free data in the southeast corner, but thats fine.  This will require an interpolation step to estimate the DEM at 0.5m resolution of the snow-on, on that grid, and finally a subtraction to produce snow depth.
