### ISSUE TITLE
Make an example producing multiple snow depth maps. 

### ISSUE THREAD

**Issue by micahjohnson150** [hpmarshall/SnowEx2020_SQLcode#5]
Once the lidar datasets are in the db, we should make an example differencing them for comparison. This would make a great notebook.

**Comment by hpmarshall** [comment]
Yes!  You could start with the easy one, just differencing the two QSI flights to make a new raster of differences.  Then the next step would be to regrid/interpolate the 2016 ASO snow-free raster to the QSI grid and difference from each of the QSI flights to get total snow depth.
